version: '3'
services:
  app:
    container_name: "store-that-bit"
    image: mateusmsouza4/store-that-bit
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app_default

networks:
  app_default: