apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-that-bit-backend
  labels:
    app: store-that-bit

spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-that-bit
  template:
    metadata:
      labels:
        app: store-that-bit
    spec:
      containers:
        - name: store-that-bit
          image: store-that-bit:latest
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "200Mi"
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
        env:
            - name: OCI_KEYCONTENT
              value: "-----BEGIN PRIVATE KEY-----
                MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC/NTcY3pyUb4                                                                                                                                                 ZR
                Naj1fDcLqIDR/e5EYJYhHEIycp0EN/tT+uBdADM1wfisG7ryU3asKTmL7/Ndep                                                                                                                                                 8r
                yLzss9N3oM0Ps0DYd57O/YSCkyjD5VWBkePpzsvZLUVohgSuKBOITGF4BMGwGB                                                                                                                                                 5z
                uF71HmdGYrWLt0fcy64NE1cnY6oSW0C3Y1DQngrKngSZdh+ghZDMzi+AbEPDLm                                                                                                                                                 89
                YE+XTakUP1By8fjyxpM87JmzbAoB2q3eFPLRy1KOOVddJFQAvknhqA+dwP/uw3                                                                                                                                                 tY
                9sgST0us8CYdInXZk8/PPYic4kR5G/Ldzyww5aPJxvVVrZf0db+jk3Ct9OgbR8                                                                                                                                                 yS
                HE3K9PpJAgMBAAECggEAUtOVc2NzBmWtFF6fOv+8xIMQkmZiISKJxfv8vOejFq                                                                                                                                                 G9
                cCp7qC2fAUluE/fLKo93F6qf7/tYO4UTkB7bn9lh4C86xPNMQrjGhTmSfhGLFh                                                                                                                                                 iw
                ynjM9ooLCZ+vslBjlKFtnJwhmKDO2h4Iiu4xzBKIgBfgNo6FRaLBWY6oMTreAC                                                                                                                                                 bh
                lMGp6CEeWgoYwFPv+W/5IUBiO04SMTKR9znksQfJLtuHiw1I3sWsvTLRsldLCu                                                                                                                                                 +J
                iNb3L4Msl2bVXtJcvEJP5c112KofXOFqRrJQr6uLiaPLtpQiRxHotoqwS5bbAQ                                                                                                                                                 7E
                /v7BmvWRKB+wR2tFFJ3fqyKj4HJvTH8peVFJo13OZQKBgQDg2MK4FzX6vS/OvI                                                                                                                                                 6f
                wSXb+5ksp8wH2GEKA8PIaqRRnQgjpuEUaPi8PHYVJNPVtWwrwGgCkknFsTzZ5H                                                                                                                                                 Pa
                VFvksXxgqdHbWV/3bE+VfItFmQrzm3eidLb1McPSW+BU2tajVPBOFBYcSo7Yh5                                                                                                                                                 fx
                jm7Loo+sgoNojqrPpPUWlwISvwKBgQDZs0uwqvN6qCZqEiNK1jizPwJtWwkPFF                                                                                                                                                 JG
                5pjN9ECS0pWO8G94Q4Qic/kcfiM3PshoxevF0OlHS+O/eWUnzBSpjvN/gFHwca                                                                                                                                                 LT
                iiPH7yxD2wAaQT9Boc1DuE7hQZny7//EQqKI3OkaInKfuvG/G5QVrO6aF8g/52                                                                                                                                                 FI
                as5m5Bgc9wKBgQDErRZ2TOdMspvU7J6dIyhoqkWsCAKyghUv22cwMggV05RBC0                                                                                                                                                 Iq
                xj98+C4aBKK/dvhttNnGFgwtvwEJX4nvWocfHhk7vI/ynNUS6k0a51wzvtETkd                                                                                                                                                 Qt
                6IX5KFSv9undj6bcK/ofcfZ9PMKCqOjBxOMpgMLIFUm49cJ360TvQ5vupQKBgQ                                                                                                                                                 CS
                SP7Fejod47vcbs+0S/rRx7dT0GZn8ZnP9sgbLNPvVP4WjM36nDPACvoMAV6ckt                                                                                                                                                 2M
                OeLSjC0VMZOaaHJmqaYAwgQxWwK0dUeaqiqdAMRX3GNXQRzGd3k81i57At/19P                                                                                                                                                 uC
                39vj573jR96KIs6rQlbhsdCrTuvKtSoTxWFolkD1xQKBgFD1rLXtG2uQ404t39                                                                                                                                                 nu
                3MilwSp77nVTROtgBVDkr3ge6KqnwvTjqp7N36z2r99ESpuPgzjm7U7Egnl0JZ                                                                                                                                                 bO
                rOjaap54ZxgQ7/5tEUJy0HBYe1cu3jFAeEL5KBFJUQ2WnxJlmaokahe3YtEV2u                                                                                                                                                 mO
                OdN0ZDiomCGrtulCIdGEsJ+8
                -----END PRIVATE KEY-----"
            - name: OCI_USER_OCID
              value: ocid1.user.oc1..aaaaaaaa7oizqmrrk47nbv25qmqpz4lqipbrpf7ny                                                                                                                                                 apfxy3tmsfzfxt4t5sq
            - name: OCI_FINGERPRINT
              value: 97:18:3a:98:48:52:7e:ac:bc:9c:15:ef:21:81:22:ca
            - name: OCI_REGION
              value: sa-saopaulo-1
            - name: OCI_TENANCY
              value: ocid1.tenancy.oc1..aaaaaaaa5yhlhqqpkdk5wq2kmc3rm4odplf55h                                                                                                                                                 rcx3gvlhfn6gjpdqdy2a4q
            - name: OCI_BUCKET_NAMESPACE
              value: gr6iwpax1dgr
            - name: OCI_BUCKET_NAME
              value: store-that-bit
            - name: OCI_DATABASE_USER
              value: ADMIN
            - name: OCI_DATABASE_PASSWORD
              value: KxupPewMUZb3sZ
            - name: OCI_ENCODING
              value: UTF-8
            - name: OCI_DATABASE_NAME
              value: files
            - name: OCI_BUCKET_PUBLIC_URL
              value: "https://swiftobjectstorage.sa-saopaulo-1.oraclecloud.com                                                                                                                                                 /v1/gr6iwpax1dgr/store-that-bit"
            - name: OCI_DATABASE_CONNECTION_STRING
              value: "mongodb://ADMIN:KxupPewMUZb3sZ@GA479F07C484704-FILES.adb                                                                                                                                                 .sa-saopaulo-1.oraclecloudapps.com:27017/files?authMechanism=PLAIN&authSource=$e                                                                                                                                                 xternal&ssl=true&retryWrites=false&loadBalanced=true"
