apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-that-bit-backend
  labels:
    app: store-that-bit

spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-that-bit
  template:
    metadata:
      labels:
        app: store-that-bit
    spec:
      containers:
        - name: store-that-bit
          image: store-that-bit:latest
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "200Mi"
          imagePullPolicy: Never
          ports:
          - containerPort: 8080